### ISSUE TITLE
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by rsanjuan87** [javaee/javamail#285]
# StandardCharsets added in sdk19
 `b64os.write(s.getBytes(StandardCharsets.UTF_8));`

_Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets 
at sun.mail.imap.protocol.IMAPProtocol.authplain(IMAPProtocol.java:715) 
at sun.mail.imap.IMAPStore.authenticate(IMAPStore.java:909) 
at sun.mail.imap.IMAPStore.login(IMAPStore.java:819) 
at sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:700) 
at mail.Service.connect(Service.java:366)_

**Comment by jmehrens** [comment]
The JavaMail Android documentation doesn't really specify what lowest Android SDK version is supported.

**Comment by bshannon** [comment]
Yes, JavaMail requires Android API level 19.  I've updated the
[JavaMail for Android page](https://javaee.github.io/javamail/Android) with that information.

**Comment by rsanjuan87** [comment]
But what can I do to use it in previous versions of Android?
 I'm developing and app and I need to it works on Android 4.0 and later

**Comment by bshannon** [comment]
I believe JavaMail 1.5.6 will work on Android 2.3.1 and later.

**Comment by rsanjuan87** [comment]
Done 1.5.6 works on Andorid 4.0 !!!
**THANKS!!!**
